package com.yjt.apt.router.compiler.constant;

public class Constant {

    // System interface
    public static final String ACTIVITY = "android.app.Activity";
    public static final String SERVICE = "android.app.Service";

    // Java type
    public static final String BYTE = "java.lang.Byte";
    public static final String SHORT = "java.lang.Short";
    public static final String INTEGER = "java.lang.Integer";
    public static final String LONG = "java.lang.Long";
    public static final String FLOAT = "java.lang.Float";
    public static final String DOUBEL = "java.lang.Double";
    public static final String BOOLEAN = "java.lang.Boolean";
    public static final String STRING = "java.lang.String";

    // Custom interface
    public static final String IPROVIDER = "com.yjt.apt.router.listener.template.IProvider";
    public static final String IPROVIDER_GROUP = "com.yjt.apt.router.listener.template.IProviderGroup";
    public static final String IINTERCEPTOR = "com.yjt.apt.router.listener.template.IInterceptor";
    public static final String IINTERCEPTOR_GROUP = "com.yjt.apt.router.listener.template.IInterceptorGroup";
    public static final String ITROUTE_ROOT = "com.yjt.apt.router.listener.template.IRouteRoot";
    public static final String IROUTE_GROUP = "com.yjt.apt.router.listener.template.IRouteGroup";

    // Log
    public static final String PREFIX_OF_LOGGER = "Router::Compiler ";

    // Options of processor
    public static final String KEY_MODULE_NAME = "moduleName";

    // Generate
    public static final String SEPARATOR = "$$";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY Router.";
    public static final String METHOD_LOAD_INTO = "loadInto";
    public static final String NAME_OF_ROOT = "Router$$Root";
    public static final String NAME_OF_PROVIDER = "Router$$Providers";
    public static final String NAME_OF_GROUP = "Router$$Group$$";
    public static final String NAME_OF_INTERCEPTOR = "Router$$Interceptors";
    public static final String PACKAGE_OF_GENERATE_FILE = "com.yjt.apt.router.routes";
}